Diagram data kasus (bentuk excel)
MZaidA/Travelendar pull request #16
Opened 2017-09-25 16:00 UTC by Gazoon007

[Dummy.xlsx](https://github.com/MZaidA/Travelendar/files/1330086/Dummy.xlsx)

2017-10-05 15:02 UTC, FakhriWN commented
Untuk Proses Bisnis Alpha Version.xlsx pada kolom "Look-up Table" 
![image](https://user-images.githubusercontent.com/28047839/31234206-77c855fa-aa18-11e7-818d-1494055db0e9.png)

di dalam comment hover terdapat tulisan: (baris 14-18)
"Jika memakai metode 1, lewati proses ini"
"Jika memakai metode 1, lalui proses ini"

jadi dilewati ataukah dilalui?

2017-10-05 15:07 UTC, FakhriWN commented
Untuk Proses Bisnis R.0.docx

No. 2B bagian 
•	User memasukkan nama event, lokasi event, tanggal event, jam event
apakah disini user input secara memilih ataukah mengetik sendiri? tolong dijelaskan per attributnya
No. 2B bagian 
•	User memasukkan nama event, lokasi event, jam event
ini sama seperti proses di atas, hanya saja tidak ada penginputan tanggal event, untuk apa ini? mohon jelaskan lagi

2017-10-05 16:42 UTC, Gazoon007 commented
Terima kasih sebelumnya atas review oleh Fakhri WN

-Terjadi kesalah pengetikan comment, yang seharusnya diubah dari
"Jika memakai metode 1, lalui proses ini" menjadi "Jika memakai metode 2, lalui proses ini"

-Ada point penjelasan yang terlewat, jadi dari tim analis sendiri memutuskan kalau pengisian selain nama event menggunakan metode button radio/dropdown, atau memilih dengan hanya pasti satu kemungkinan. Sedangkan nama event (atau boleh ditambah atribut baru bernama deskripsi event) menggunakan penginputan manual atau ketik sendiri

Jika ada yang kurang jelas, silahkan direview ulang kembali, Terima kasih

2017-10-06 01:18 UTC, FakhriWN commented
Apakah kita tidak memerlukan data User seperti Nama dan email user? @Gazoon007 @RizkaFa

2017-10-06 03:27 UTC, Gazoon007 commented
Tergantung ketua @MZaidA jika setuju mengimplementasikan account management screen (login/logoff) seperti yang saya design dalam screenflow diagram, maka data user seperti nama dan email user dicantumkan

2017-10-06 08:20 UTC, nmryn commented
Ada beberapa yang ingin saya konfirmasi dan tanyakan:
1. Jadi user tidak menginput tgl & jam mulai event, serta tgl & jam akhir event? Tapi user menginput tgl & jam keberangkatan ke lokasi (optional), serta tgl & jam sampai di lokasi?
2. Apakah user menginput deskripsi/keterangan event pada saat create event?
3. Apakah user tidak memilih output suggestions? Jadi hanya ditampilkan banyak saran di created event?
4. Lalu apa saja yang diterdapat dalam suggestion (moda transportasi, ...)? Apakah tgl & jam keberangkatan (bila user tidak menginput) serta estimasi waktu terdapat dalam suggestion selain moda transportasi?

Terimakasi...

2017-10-06 08:38 UTC, nmryn reviewed
Ada beberapa yang ingin saya konfirmasi dan tanyakan:

1. Jadi user tidak menginput tgl & jam mulai event, serta tgl & jam akhir event? Tapi user menginput tgl & jam keberangkatan ke lokasi (optional), serta tgl & jam sampai di lokasi?
2. Jadi user tidak hanya menginput lokasi akhir event? Tapi juga menginput lokasi awal event?
3. Apakah user menginput deskripsi/keterangan event pada saat create event?
4. Apakah user tidak memilih output suggestions? Jadi hanya ditampilkan banyak saran di created event?
5. Lalu apa saja yang diterdapat dalam suggestion (moda transportasi, ...)? Apakah tgl & jam keberangkatan (bila user tidak menginput) serta estimasi waktu terdapat dalam suggestion selain moda transportasi?
6. Apakah user bisa menambah sendiri data lokasi/kendaraan ke dalam database selain admin?

Terimakasi

2017-10-08 07:59 UTC, Gazoon007 commented
Terima kasih untuk review yang komprehensif oleh @nmryn 

1. Betul, karena perbedaan diantara keduanya hanyalah masalah patokan, tim analis sepakat untuk memasang patokannya mengikti kaidah arrival departure. Dan sperti yg saya katakan, departure sifatnya optional

2. Kurang tepat, user MEMILIH lokasi awal dan akhir dengan single line select box seperti screenshot dibawah ini https://mdn.mozillademos.org/files/4517/all-select.png jadi terdapat 2 single line select box, satu yg lok awal satu lagi yg lok akhir, dan user bisa juga menginputkan lok awal & akhir pada select box yang sama untuk membantu admin melengkapi data

3. Balik lagi ke screenflow diagram silahkan dilihat, bahwa deskripsi event diinput pada Event Creation Screen. (Jika butuh informasi tambahan mengenai Screen Flow Diagram, silahkan hubungi saya)

4. Pada Proses Bisnis Alpha Version dijelaskan di bagian proses ke 8 bahwa "Mengirimkan 1 diantara suggestion bermacam suggestion (kendaraan yang lain jika ada) berdasarkan data waktu tercepat", maka akan hanya ada 1 yang dipilih oleh user dari berbagai suggestion

5. Yang terdapat dalam suggestion yang terpenting adalah, moda kendaraan beserta jarak dan waktu tempuh. Untuk tgl dan waktu hanya sebagai informasi diluar suggestion, karena apapun suggestionnya, tgl dan waktu akan selalu sama. Lalu perlu diketahui bahwa selalu akan ada arrival departure jika terdapat travelling didalamnya, bila user tidak menginput departure maka tidak terdapat perjalanan disana. (Point yg satu ini mungkin membingungkan, bila belum sepenuhnya paham, saat meeting kita diskusikan lebih lanjut)

6. Seperti yg saya jelaskan pada point ke dua, user bisa menambahkan sendiri data lokasi, namun untuk data kendaraan sendiri pun bisa, hanya saja penginputannnya di screen yang berbeda, sekali lg saya sarankan untuk mengacu pada Screen Flow Diagram yg sudah saya buat

Terima kasih sekali lagi kepada @nmryn saya apresiasi atas review baik ini, saya sarankan kepada nino untuk mengkomunikasikan hasil ini kepada divisi yg terkait, guna menyelaraskan pemahaman dan bila ada kendala silahkan kontak saya pada jam yg saya tentukan yaitu pada hari KBM (senin-jumat), serta minggu dari pukul 2.

2017-10-08 12:39 UTC, syamcode commented
Pada review ini saya ingin bertanya kepada @Gazoon007 
1. Mengambil pertanyaan dari @nmryn, untuk pengguna apakah perlu menginput lokasi awal juga? bukankah normalnya pengguna saat merencanakan kegiatan hanya mengisi lokasi eventnya saja. Lalu pada data kasus juga bukankah pada satu agenda hanya terdapat 1 lokasi yaitu Tempat.
![image](https://user-images.githubusercontent.com/9907952/31316864-0b1c38b4-ac60-11e7-8f0f-5f389e046149.png)
2. Dimana proses penyaranan kendaraan dan keberangkatan dilakukan? saat mengisi 1 e
![image](https://user-images.githubusercontent.com/9907952/31316864-0b1c38b4-ac60-11e7-8f0f-5f389e046149.png)
vent apakah setelah semua event telah diinputkan?
3. Apakah aplikasi ini bisa menghandle user untuk menggunakan transportasi umum? jika iya, seperti apa struktur dari moda transportasi dan lookup table yang diberikan. karena beberapa transportasi umum memiliki jadwal keberangkatan yang tetap sehingga waktu departure harus menyesuaikan dengan jadwal keberangkatan transportasi umum tersebut.
4. Pada data kasus, ada agenda yang memiliki lokasi awal di Bandara Depati dan lokasi akhir di Bandara Soetta. Lalu di lookup table ada beberapa suggestion mengenai 2 lokasi tersebut. Pertanyaan saya adalah apakah aplikasi perlu untuk menyarankan kendaraan kembali untuk agenda tersebut?. Bukankah apabila user memiliki agenda dengan lokasi awal dan akhir bandara sudah pasti akan menggunakan pesawat?
5. Mengomentari dari jawaban no 5 dari pertanyaan @nmryn, mengapa jarak tempuh perlu di suggestkan. Bukannya user hanya memerlukan kapan harus berangkat ke lokasi dan kendaraan apa yang akan digunakan?

Sekian pertanyaan yang ingin saya ajukan, apabila ada pertanyaan yang kurang dimengerti bisa dituliskan di comment. Terima Kasih

2017-10-08 13:51 UTC, MZaidA requested changes
review dari saya
1. apakah tidak ada proses pengguna melihat sebuah detail sebuah event? setelah event tersebut ditambahkan
2. diproses bisnis versi alfarish dan rizka mohon segera disatukan karena terdapat bagian bagian yang tidak ada di salah satu versi
3. apa saja yang ditampilkan saat event dapat dilihat perbulan/perminggu/perhari? mohon diperjelas
4. mohon diperjelas juga dibagian lain apa yang user bisa lihat dari aplikasi di halaman aplikasi itu

2017-10-08 14:45 UTC, afadhitya commented
Saya ingin sedikit mereview pada proses bisnis @RizkaFa  pada file "Proses Bisnis versi R.0"
1. Untuk homepagenya sendiri itu adalah harus berupa kalender, maka opsi fungsi kalender mungkin bisa dihilangkan karna itu sudah bagian dari homepage
2. Untuk tampilan kalender tidak hanya perhari atau perbulan tapi bisa juga perminggu atau list event dalam satu minggu

Review pada proses bisnis @Gazoon007  pada file "Proses Bisnis Alpha Version"
1. Jangan lupa user juga perlu men-input jam mulai dan selesai event
![8 okt 2017 21 38 55](https://user-images.githubusercontent.com/23567058/31317814-dec6f09e-ac71-11e7-977c-9abd079453f8.jpeg)
2. Untuk transportasi jangan hanya yang sudah user setting, harus ada transportasi yang pasti digunakan atau ditampilkan suggestnya ke semua user, contohnya pesawat, karna jika user tidak menset kendaraan pesawat maka untuk jarak jauh mungkin hanya akan ada suggest mobil jika ia menset mobil

Mungkin hanya sedikit review dari saya karna sudah disebutkan semua oleh @FakhriWN @syamcode dan @nmryn 

Sedikit tambahan dari saya, dan ini juga untuk semua, biasakan file dimasukan ke dalam folder dan folder dinamai sesuai dengan nama pekerjaannya, misal untuk hal ini folder dinamakan "proses bisnis". Meskipun ini dalam branch yang terpisah dengan master tapi tetap saja tidak enak dipandangnya jika disimpan di luar folder.
Terima kasih. Semoga Allah selalu melancarkan kerja kita.

2017-10-09 03:35 UTC, Gazoon007 commented
Terima kasih untuk reviewnya oleh @syamcode 

1. Ingin meluruskan dari pertanyaan hisyam, lokasi awal perlu diinputkan di setiap kegiatan travelling, karena jarak dan waktu tempuh tersedia dan dapat dimuat jika mempunyai 2 titik lokasi, yaitu lokasi awal dan lokasi akhir. 
Satu Agenda bisa memuat banyak tempat, perhatikan data kasus v2.0 di sample yang saya highlight abu abu, disana dijelaskan bahwa "Mengunjungi Sekolah Lain" itu merupakan 1 nama event yang memuat banyak lokasi, jadi tim analis memutuskan untuk mendefinisikan 1 nama event bisa memuat banyak lokasi

2. Saran saya untuk ini, adakan suggestion stelah kondisi smua tempat dalam satu event terinput. Patokannya adalah per nama event.

3. Tim analis menargetkan untuk dapat menggunakan transportasi umum. Buat saja suatu kondisi dimana saat pemilihan transportasi pribadi, departure diinputkan manual, namun jika transportasi umum dipilih maka departure berupa pilihan (single line select box) yang mengacu pada jadwal keberangkatan transportasi umum.

4. Tidak perlu, hal ini sudah saya jelaskan pada comment cell di proses bisnis urutan ke delapan pada Proses Bisnis Alpha Version.xlsx
Dan perlu diluruskan lagi bahwa, data kasus yang memuat lokasi awal/akhir nya bandara ditiadakan saja, karena pesawat masuk kedalam suggestion, jadi berikutnya akan direvisi lagi data kasusnya.
![image](https://user-images.githubusercontent.com/27797762/31324501-69e612a2-acdd-11e7-9686-32b66a8c0f43.png)

5. Untuk ini, saran saya jarak tempuh pun dimasukkan kedalam suggestion namun sebagai informasi tambahan, acuan prioritas utama adalah waktu tempuh karena berpatok pada kapan arrival yang diset.
Alasan saya kenapa jarak tempuh dijadikan suggestion juga karena ada user yang mempertimbangkan jarak terdekat dengan waktu yang sedikit lebih lama, ketimbang jarak yang jauh dengan waktu yang cepat. Meskipun keduanya sama-sama tidak mengoffsetkan arrival yang diset, namun akan ada kondisi dimana user mempertimbangkan jarak.

Kalau ada yang kebingungan bisa hubungi saya pada hari KBM (senin-jumat), serta minggu dari pukul 2. Terima Kasih banyak

2017-11-27 13:30 UTC, closed without merging